# -*- coding: utf-8 -*-
"""data_laoder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qdcltNi3ok2V8osBycYoyvIgyXr-Rmfo
"""

# data_loader.py

import os
import numpy as np
from sklearn.datasets import load_files
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt

def mount_drive():
    """Mount Google Drive (for Colab)."""
    from google.colab import drive
    drive.mount('/content/drive')

def load_dataset(path):
    """
    Load dataset file paths and labels.
    Returns: files, targets, target_labels
    """
    data = load_files(path)
    files = np.array(data['filenames'])
    targets = np.array(data['target'])
    target_labels = np.array(data['target_names'])
    return files, targets, target_labels

def count_images(folder='dataset-augmented'):
    """
    Print number of images per class in train, valid, test folders.
    """
    main_folders = ['train', 'valid', 'test']
    for main_folder in main_folders:
        folder_path = os.path.join(folder, main_folder)
        if os.path.isdir(folder_path):
            print(f"\nIn folder '{main_folder}':")
            garbage_types = os.listdir(folder_path)
            for garbage_type in garbage_types:
                subfolder_path = os.path.join(folder_path, garbage_type)
                if os.path.isdir(subfolder_path):
                    image_files = [f for f in os.listdir(subfolder_path)
                                   if f.lower().endswith(('jpg','jpeg','png'))]
                    num_images = len(image_files)
                    print(f"  {garbage_type} folder contains {num_images} images.")

def get_data_generators(train_dir, valid_dir, test_dir,
                        img_height=224, img_width=224, batch_size=50):
    """
    Create train, validation, and test generators.
    Returns: train_dataset, valid_dataset, test_dataset
    """
    data_gen_train = ImageDataGenerator(rescale=1./255,
                                        fill_mode='nearest',
                                        vertical_flip=True,
                                        horizontal_flip=True,
                                        zoom_range=0.2,
                                        shear_range=0.2,
                                        rotation_range=40,
                                        width_shift_range=0.2,
                                        height_shift_range=0.2)

    data_gen_valid = ImageDataGenerator(rescale=1./255)
    data_gen_test = ImageDataGenerator(rescale=1./255)

    train_dataset = data_gen_train.flow_from_directory(
        train_dir,
        class_mode="categorical",
        target_size=(img_height, img_width),
        batch_size=batch_size,
        shuffle=True
    )

    valid_dataset = data_gen_valid.flow_from_directory(
        valid_dir,
        class_mode="categorical",
        target_size=(img_height, img_width),
        batch_size=batch_size,
        shuffle=False
    )

    test_dataset = data_gen_test.flow_from_directory(
        test_dir,
        class_mode="categorical",
        target_size=(img_height, img_width),
        batch_size=batch_size,
        shuffle=False
    )

    return train_dataset, valid_dataset, test_dataset

def show_samples(dataset, num_samples=9):
    """
    Display sample images from a dataset generator.
    """
    images, labels_class = next(dataset)
    classes = dataset.class_indices

    plt.figure(figsize=(8,9))
    for i in range(min(num_samples, len(images))):
        label = [j for j in classes if classes[j] == np.argmax(labels_class[i])][0]
        ax = plt.subplot(3, 3, i + 1)
        plt.imshow((images[i]*255.).astype("uint8"))
        plt.title(label)
        plt.axis('off')
    plt.tight_layout()
    plt.show()